Updated the model to Claude v3
aws-samples/amazon-bedrock-samples pull request #113
Opened 2024-03-13 15:51 UTC by barnesrobert

* Updated the model to Claude v3
* Added a CloudFormation parameter for the Bedrock model ID
* Updated Lambda function runtime to 3.12

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-15 14:29 UTC, barnesrobert reviewed
Reviewed.

2024-04-19 13:38 UTC, rstrahan requested changes
Hi Rob, Thanks! I left a few comments inline. 
Can you also add a few notes to the PR re:
- what models have you have tested for compatibility.. does it work with the entire claude-3 family (it should) but does it also have backward compatibility with the whole claude-2 family? (I'm not sure if all claude-2 models support the new messages api)
- Any other testing you've done to validate it.
Cheers
Bob

2024-04-19 17:05 UTC, barnesrobert reviewed
Updated the template based on reviewer recommendations.

2024-04-19 17:05 UTC, barnesrobert commented on generative-ai-solutions/recordings-summary-generator/recordings-summary-generation.yaml
> +  BedrockModelId:
Good point. I was trying to make this future-friendly by leaving the value freeform, but constraining the value is a better present-friendly approach.

2024-04-19 18:29 UTC, rstrahan approved these changes
LGTM

2024-04-24 17:56 UTC, barnesrobert reviewed
Changes reviewed.

2024-04-24 17:56 UTC, merged

2024-05-03 15:22 UTC, amcginlay commented
@barnesrobert FYI I get an AccessDeniedException.
I managed to fix this by updating the `BedrockPermissions` in the `InvokeBedrockModelFunctionRole` resource as follows:

```
        - PolicyName: BedrockPermissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource:
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-v2
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-sonnet-20240229-v1:0
                  - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-3-haiku-20240307-v1:0
```

2024-05-08 13:35 UTC, barnesrobert commented
Ah, thanks, @amcginlay. I created a [pull request](https://github.com/aws-samples/amazon-bedrock-samples/pull/155) to update the IAM role policy. The least-privilege IAM policy will be constrained to the selected model ID.