change to point to faiss
aws-samples/amazon-bedrock-samples pull request #127
Opened 2024-04-01 18:30 UTC by tanayz

Added code to body_json to reflect change to point to faiss post 03/27

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-04-01 18:34 UTC, tanayz commented
Post 03/27 this notebook doesn't work and throws error as the index creation process doesn't point to FAISS. With this change it can point back to FAISS and I was able to run this notebook in sagemaker studio.

2024-04-12 01:25 UTC, mani-aiml requested changes
small update to change space_type to l2

2024-04-12 01:25 UTC, mani-aiml commented on knowledge-bases/0_create_ingest_documents_test_kb.ipynb
> +    "                 \"space_type\": \"innerproduct\",\n",
"space_type" should be "l2"

2024-04-18 22:16 UTC, bs258q approved these changes

2024-04-30 16:53 UTC, closed without merging