Amazon Bedrock Agents for Finanacial Analyst Code Samples
aws-samples/amazon-bedrock-samples pull request #159
Opened 2024-05-10 19:09 UTC by ucegbe

*Description of changes:* I added the folder for the amazon bedrock agents examples for financial investment research that Sovik and team worked on 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-05-13 22:04 UTC, mttanke requested changes
We need to make the code more automated and remove manual steps plus too permissive roles

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-PortfolioTool-BedrockAgent-9a4cdb9f-14b9-4658-9720-537735bf2b1c.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-SentimentDetecttion-BedrockAgent-6aebee60-d2df-464c-b652-b93e2aef7b3a.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-StockQuery-BedrockAgent-4bed2482-a84f-4d9b-b53c-37220fd4b9bb.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-TextractAsyncInvocationFunction-759363ea-7b4b-411c-a96f-b137a595387b.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-TextractProcessingFunction-b6054c5e-0286-4cfb-a2f3-55d408a9972c.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/files/FSI-Transcribe-66a4860d-390a-4af5-aa1b-05fb469be7ac.zip
we should make those available as files and zip them + package for S3 with code

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kb6.png
remove KB ID

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kb7.png
remove the S3 url

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kendra_sync.png
what is kendra being used for?

2024-05-13 22:04 UTC, mttanke commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/stack_resources.png
remove physical id

2024-05-20 12:44 UTC, oashton commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/README.md
> +First, make an S3 bucket. Go to S3 page in AWS, click "Create bucket". Then enter a bucket name, which should be universally unique. Take a note of the name, because we will need it in following sect
before proceeding with the changes:
1. Is it ok if we upload the files (i.e.: .zip lambda layers, pdf, json and csv) to the “aws-blogs-artifacts-public” bucket and then do the copy of file to the S3 account?, please see [this](https://github.com/aws-samples/agentsforbedrock-retailagent/blob/main/template.yml) as a reference.
2. About the lambda source code .zip files, ¿is it ok if we put the source code inline in the CF template?

2024-06-10 15:53 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kb6.png
done

2024-06-10 15:54 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kb7.png
done

2024-06-10 15:54 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/stack_resources.png
done

2024-06-10 16:09 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/images/kendra_sync.png
original implementation with langchain used Kendra, I have removed the pictures as the current implementation uses KB

2024-06-10 16:10 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/README.md
> +This file walks you through how to set up the infrastructure and applications, and run the code to create a multi-modal agent using Amazon Bedrock. The blog post provides a detailed discussion of thi
Yes

2024-06-10 16:50 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/README.md
> +<img src="images/bedrock-access.JPG" width="680"/>
fixed

2024-06-10 16:53 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/README.md
> +[AWS CloudShell](https://aws.amazon.com/cloudshell/) allos you to explore and manage AWS resources from a terminal in your browser
fixed

2024-06-10 16:54 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/README.md
> +See [CONTRIBUTING](CONTRIBUTING.md#security-issue-notifications) for more information.
done

2024-06-10 16:55 UTC, ucegbe commented on agents-for-bedrock/use-case-examples/ai-powered-assistant-for-investment-research/AWS Pricing Calculator Estimation.pdf
I have removed it as the solution will be run in workshop accounts and cost is very dynamic as model pricing can change

2024-06-10 16:56 UTC, ucegbe reviewed
I have made the non-cloudformation changes requested.

2024-06-10 22:18 UTC, mttanke approved these changes

2024-06-10 22:19 UTC, merged