contextual chatbot using bedrock knowledge bases
aws-samples/amazon-bedrock-samples pull request #73
Opened 2024-01-31 00:53 UTC by mchugh7153

*Issue #, if available:*

*Description of changes:*
Added new code folder and code files for Contextual Chatbot using Bedrock Knowledge Bases. This code is in support for accompanying blog post. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-31 14:50 UTC, mttanke requested changes

2024-02-02 22:30 UTC, mchugh7153 commented on rag-solutions/contextual-chatbot-using-knowledgebase/cfn/DeployKnowledgeBase.yaml
> +        - 'arn:aws:iam::aws:policy/IAMFullAccess'
removed wide permissive policy, cleaned/optimized up the roles and policies in yaml file

2024-02-02 22:31 UTC, mchugh7153 commented on rag-solutions/contextual-chatbot-using-knowledgebase/images/kb-vectorstore.jpg
Yes, replaced this image with latest models. And, also modified couple of other images to include annotations lines and arrows for further clarity too

2024-02-02 22:36 UTC, mchugh7153 commented
Fixed the changes requested, please review again, provide approval and merge

2024-02-02 22:42 UTC, mttanke approved these changes

2024-02-02 22:42 UTC, merged